version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: policy-postgres
    environment:
      POSTGRES_DB: policy_issuance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - policy-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: policy-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - policy-network

  redis:
    image: redis:7-alpine
    container_name: policy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - policy-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  policy-network:
    driver: bridge
